CREATE DATABASE libros;
GO;
USE libros;
CREATE TABLE IF NOT EXISTS libros(
    id BIGINT UNSIGNED AUTO_INCREMENT NOT NULL,
    isbn VARCHAR(255) NOT NULL,
    titulo VARCHAR(255) NOT NULL,
    anyo SMALLINT NOT NULL,
    PRIMARY KEY (id)
);